[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/exchange-token"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[build.environment]
  SPOTIFY_CLIENT_ID = "YOUR_SPOTIFY_CLIENT_ID"  # Replace with your actual Client ID in Netlify's UI
  REDIRECT_URI = "https://fullscreenalbumimagefy.netlify.app/callback"